*===============================================================================
*Project AKM-SDR
*===============================================================================
/*
	Author: 	César Garro-Maín
	Purpose: 	relabels restricted use Surveys of Doctorate Recipients
*/
*===============================================================================

cap label var lwnvr "never worked"
cap label var nwfam "reasons for not working: family responsibilities"
cap label var nwill "reasons for not working: illness/disability"
cap label var nwocna "reasons for not working: suitable job not available"
cap label var nwlay "reasons for not working: layoff"
cap label var nwnond "reasons for not working: did not need/want to work"
cap label var nwot "reasons for not working: other"
cap label var nwret "reasons for not working: retired"
cap label var nwrtyr "reasons for not working: retired year"
cap label var nwstu "reasons for not working: student"
cap label var wrkg "working for pay or profit during reference week"
cap label var lfstat "labor force status"
cap label var lookwk "not working, looking for work"
cap label var strtmn "month principal job started"
cap label var strtyr "year principal job started"
cap label var n2ocpr "job code for principal job - best code"
cap label var n2ocprx "job code for principal job - reported code (do not use for analysis - use best code)"
cap label var n2ocprmg "job code for principal job (major group)"
cap label var n2ocprng "job code for principal job (minor group)"
cap label var nrchg "reason for working outside field of highest degree: career change"
cap label var nrfam "reason for working outside field of highest degree: family-related reasons"
cap label var nrocna "reason for working outside field of highest degree: suitable job not available"
cap label var nrloc "reason for working outside field of highest degree: job location"
cap label var nrot "reason for working outside field of highest degree: other"
cap label var nrpay "reason for working outside field of highest degree: pay/promotion"
cap label var nrcon "reason for working outside field of highest degree: working conditions"
cap label var nrrea "most important reason for working outside field of highest degree"
cap label var nrsec "second most important reason for working outside field of highest degree"
cap label var pdix "principal job postdoc indicator"
cap label var pdexpect "reason for taking postdoc: generally expected in field"
cap label var pdempl "reason for taking postdoc: other employment not available"
cap label var pdother "reason for taking postdoc: other"
cap label var pdtrout "reason for taking postdoc: training in area outside phd field"
cap label var pdperpl "reason for taking postdoc: work with specific person or place"
cap label var pdtrain "reason for taking postdoc: additional training in phd field"
cap label var pdpri "most important reason for taking postdoc"
cap label var pdsec "second most important reason for taking postdoc"
cap label var ocedrlp "extent that principal job is related to highest degree"
cap label var ftpret "previously retired"
cap label var ftprtyr "year previously retired"
cap label var wksyr "indicator for working 52 weeks per year"
cap label var wkslyr "number of weeks worked per year if less than 52 weeks"
cap label var wkswk "principal job salary:  weeks per year basis"
cap label var hrswk "principal job: hours per week typically worked"
cap label var n2oclst "job code for last job - best code"
cap label var n2oclstx "job code for last job - reported code (do not use for analysis - use best code)"
cap label var n2ocmlst "job code for last job (major group)"
cap label var n2ocnlst "job code for last job (minor group)"
cap label var lwmn "month last worked"
cap label var lwyr "year last worked"
cap label var chchg "reason for changing employer or job: change in career/professional interests"
cap label var chfam "reason for changing employer or job: family-related reasons"
cap label var chlay "reason for changing employer or job: laid off/job terminated"
cap label var chloc "reason for changing employer or job: job location"
cap label var chot "reason for changing employer or job: other"
cap label var chpay "reason for changing employer or job: pay, promotion"
cap label var chret "reason for changing employer or job: retired"
cap label var chsch "reason for changing employer or job: school-related reasons"
cap label var chcon "reason for changing employer or job: working conditions"
cap label var wrkgp "employment status indicator, comparing current and previous reference weeks"
cap label var promtgi "attended professional meetings in past year"
cap label var prmbr "number of professional society memberships"
cap label var emsmi "employment status (same job/employer?), current and previous reference weeks"
cap label var acadna "academic position: not applicable"
cap label var acadothr "academic position: other"
cap label var acadpdoc "academic position: postdoc"
cap label var acadpres "academic position: president/provost/chancellor"
cap label var acadra "academic position: research assistant"
cap label var acadrchf "academic position: research faculty"
cap label var acadta "academic position: teaching assistant"
cap label var acadtchf "academic position: teaching faculty"
cap label var jobins "available benefits: health insurance"
cap label var jobpens "available benefits: pension/retirement plan"
cap label var jobproft "available benefits: profit-sharing plan"
cap label var jobvac "available benefits: paid vacation/sick/personal days"
cap label var carneg "carnegie classification for employer if a postsecondary educational institution - 1994 carnegie code"
cap label var carn05c "carnegie classification for employer if a postsecondary educational institution - 2005 carnegie code"
cap label var instcod "institution code for employer if a postsecondary educational institution"
cap label var facrank "faculty rank"
cap label var emed "indicator for educational institution employer"
cap label var pubpri "public/private indicator for employer if a postsecondary educational institution - 1994 carnegie value"
cap label var pbpr05c "public/private indicator for employer if a postsecondary educational institution - 2005 carnegie value"
cap label var tensta "tenure status"
cap label var teni "tenure status indicator"
cap label var tenyr "tenure year"
cap label var edtp "type of educational institution employer"
cap label var emrg "region code for employer"
cap label var emus "employer location (u.s./non-u.s.)"
cap label var newbus "new business"
cap label var nedtp "employer type (not taking into account if it was an educational institution)"
cap label var emsecdt "employer sector (detailed codes)"
cap label var emsecsm "employer sector (summary codes)"
cap label var emsize "employer size"
cap label var emst "state/country code for employer"
cap label var emtp "employer type (taking into account educational institutions)"
cap label var facadv "importance of job's opportunities for advancement"
cap label var facben "importance of job's benefits"
cap label var facchal "importance of job's intellectual challenge"
cap label var facind "importance of job's degree of independence"
cap label var facloc "importance of job's location"
cap label var facresp "importance of job's level of responsibility"
cap label var facsal "importance of job's salary"
cap label var facsec "importance of job's security"
cap label var facsoc "importance of job's contribution to society"
cap label var mgroth "job required technical expertise at the bachelor's level or higher:  other fields (e.g. health/business)"
cap label var mgrnat "job required technical expertise at the bachelor's level or higher:  eng, comp sci, math, nat sciences"
cap label var mgrsoc "job required technical expertise at the bachelor's level or higher:  social sciences"
cap label var pjfam "reason worked part-time:  family responsibilities"
cap label var pjocna "reason worked part-time:  full-time job not available"
cap label var pjhaj "reason worked part-time:  held another job"
cap label var pjnond "reason worked part-time:  did not need/want to work full-time"
cap label var pjot "reason worked part-time:  other"
cap label var pjret "reason worked part-time:  previously or semi-retired"
cap label var pjretyr "reason worked part-time: previously or semi-retired year"
cap label var pjstu "reason worked part-time:  student"
cap label var pjwtft "want to work full-time on principal job indicator"
cap label var satadv "satisfaction principal job's opportunities for advancement"
cap label var satben "satisfaction principal job benefits"
cap label var satchal "satisfaction principal job's intellectual challenge"
cap label var satind "satisfaction principal job's degree of independence"
cap label var satloc "satisfaction principal job's job location"
cap label var jobsatis "job satisfaction"
cap label var satresp "satisfaction principal job's level of responsibility"
cap label var satsal "satisfaction principal job salary"
cap label var satsec "satisfaction principal job's job security"
cap label var satsoc "satisfaction principal job's contribution to society"
cap label var supdir "number of people supervised directly"
cap label var supind "number of people supervised through subordinates"
cap label var supwk "supervised others in principal job indicator"
cap label var actcap "primary/secondary work activity on principal job: computer applications"
cap label var actded "primary/secondary work activity on principal job: development or design"
cap label var actmgt "primary/secondary work activity on principal job: management/sales"
cap label var actres "primary/secondary work activity on principal job: basic or applied research"
cap label var actrd "primary/secondary work activity on principal job: basic research/applied research/development/design"
cap label var actrdt "primary/secondary work activity on principal job: basic research/applied research/development/design/teaching"
cap label var acttch "primary/secondary work activity on principal job: teaching"
cap label var wapri "work activity spent most hours on in principal job"
cap label var waprsm "summarized primary work activity"
cap label var wasec "work activity spent second most hours on in principal job"
cap label var wascsm "summarized secondary work activity"
cap label var waacc "work activity on principal job (10% indicator): accounting, finance, contracts"
cap label var waaprsh "work activity on principal job (10% indicator): applied research"
cap label var wabrsh "work activity on principal job (10% indicator): basic research"
cap label var wacom "work activity on principal job (10% indicator): computer applications"
cap label var wadsn "work activity on principal job (10% indicator): design"
cap label var wadev "work activity on principal job (10% indicator): development"
cap label var wamgmt "work activity on principal job (10% indicator): managing or supervising people/project"
cap label var waot "work activity on principal job (10% indicator): other"
cap label var waemrl "work activity on principal job (10% indicator): human resources"
cap label var waprod "work activity on principal job (10% indicator): production, operations, maintenance"
cap label var wasvc "work activity on principal job (10% indicator): professional services"
cap label var waqm "work activity on principal job (10% indicator): quality or productivity management"
cap label var wasale "work activity on principal job (10% indicator): sales, purchasing, marketing"
cap label var watea "work activity on principal job (10% indicator): teaching"
cap label var wtreasn "most important reason for taking work-related training"
cap label var wtrskl "reason for attending work-related training: acquire further skills/knowledge"
cap label var wtrchoc "reason for attending work-related training: facilitate occupation change to different field"
cap label var wtrem "reason for attending work-related training: required/expected by employer"
cap label var wtrlic "reason for attending work-related training: licensure/certification"
cap label var wtropps "reason for attending work-related training: increase advancement opportunities in current occupation"
cap label var wtrot "reason for attending work-related training: other"
cap label var wtrpers "reason for attending work-related training:  leisure/personal interest"
cap label var wktrni "attended work-related training"
cap label var salary "salary (annualized)"
cap label var earn "total earned income before deductions in previous year"
cap label var fsdod "federal agency supporting work: defense"
cap label var fsded "federal agency supporting work: education"
cap label var fsdoe "federal agency supporting work: energy"
cap label var fshhs "federal agency supporting work: hhs"
cap label var fsnih "federal agency supporting work: nih"
cap label var fsnsf "federal agency supporting work: nsf"
cap label var fsot "federal agency supporting work: other"
cap label var fsdk "federal agency supporting work: agency unknown"
cap label var govsup "federal government support indicator"
cap label var baacyr "academic year of award for first bachelor's degree"
cap label var bamn "month of award of first bachelor's degree"
cap label var bayr "year of award of first bachelor's degree"
cap label var baayr3 "year of award of first bachelor's degree (3-year intervals)"
cap label var baayr5 "year of award of first bachelor's degree (5-year intervals)"
cap label var baind " indicator of whether respondent received a ba-level degree"
cap label var nbamed "field of study of for first bachelor's degree - best code"
cap label var nbamedx "field of study for first bachelor's degree - reported code (do not use for analysis - use best code)"
cap label var nbamemg "field of study for first bachelor's degree (major group)"
cap label var nbameng "field of study for first bachelor's degree (minor group)"
cap label var bacarn "carnegie classification for school awarding first bachelor's degree - 1994 carnegie code"
cap label var bacrn05c "carnegie classification for school awarding first bachelor's degree - 2005 carnegie code"
cap label var baincd "institution code for school awarding first bachelor's degree"
cap label var bapbpr "public/private status of postsecondary institution awarding first bachelor's degree - 1994 carnegie value"
cap label var bapbp05c "public/private status of postsecondary institution awarding first bachelor's degree -- 2005 carnegie value"
cap label var bargn "location of school awarding first bachelor's degree (region code)"
cap label var badgrus "location of school awarding first bachelor's degree (u.s./non-u.s.)"
cap label var bast "location of school awarding first bachelor's degree (state/country code)"
cap label var mrdacyr "academic year of award for most recent degree"
cap label var mrmn "month of award of most recent degree"
cap label var mryr "year of award of most recent degree"
cap label var mr3yr "year of award of most recent degree (3-year intervals)"
cap label var mr5yr "year of award of most recent degree (5-year intervals)"
cap label var mrskl "reason for obtaining most recent degree: acquire further skills in field"
cap label var mradv "reason for obtaining most recent degree: increase opportunities for promotion, advancement, higher salary"
cap label var mrcar "reason for obtaining most recent degree: further education before career"
cap label var mrchg "reason for obtaining most recent degree: change academic/occupational field"
cap label var mrem "reason for obtaining most recent degree: required/expected by employer"
cap label var mrlic "reason for obtaining most recent degree: licensure/certification"
cap label var mrot "reason for obtaining most recent degree: other"
cap label var mrint "reason for obtaining most recent degree: leisure/personal interest"
cap label var mrgrd "reason for obtaining most recent degree: prepare for grad school/further education"
cap label var mrdg "most recent degree type"
cap label var nmrmed "field of study of major for most recent degree - best code"
cap label var nmrmedx "field of study of major for most recent degree - reported code (do not use for analysis - use best code)"
cap label var nmrmemg "field of study of major for most recent degree (major group)"
cap label var nmrmeng "field of study of major for most recent degree (minor group)"
cap label var mrcarn "carnegie classification for school awarding most recent degree - 1994 carnegie code"
cap label var mrcrn05c "carnegie classification for school awarding most recent degree - 2005 carnegie code"
cap label var mrincd "institution code for school awarding most recent degree"
cap label var mrpbpr "public/private status of postsecondary institution awarding most recent degree - 1994 carnegie value"
cap label var mrpbp05c "public/private status of postsecondary institution awarding most recent degree - 2005 carnegie value"
cap label var mrrgn "location of school awarding most recent degree (region code)"
cap label var mrdgrus "location of school awarding most recent degree (u.s./non-u.s.)"
cap label var mrst "location of school awarding most recent degree (state/country code)"
cap label var acccep "school related costs for course taking paid by employer"
cap label var nacedmg "code for field of study during reference week (major group)"
cap label var nacedng "code for field of study during reference week (minor group)"
cap label var naced "code for field of study during reference week - best code"
cap label var nacedx "code for field of study during reference week - reported code"
cap label var acfpt "taking courses/enrolled during reference week: enrollment status"
cap label var acsin "taking courses and/or enrolled during reference week indicator"
cap label var acskl "reason for taking courses during reference week: gain further skills in field"
cap label var acadv "reason for taking courses during reference week: increase advancement opportunities"
cap label var accar "reason for taking courses during reference week: further education before career"
cap label var acchg "reason for taking courses during reference week:  change academic/occupational field"
cap label var acem "reason for taking courses during reference week: expected/required by employer"
cap label var aclic "reason for taking courses during reference week: licensure/certification"
cap label var acot "reason for taking courses during reference week: other"
cap label var acint "reason for taking courses during reference week: leisure/personal interest"
cap label var acgrd "reason for taking courses during reference week: prepare for graduate school/further education"
cap label var acdrg "type of degree working on during reference week"
cap label var tcdgcmp "completed degree between previous survey reference month/year and current survey reference month/year"
cap label var hdacyr "academic year of award for highest degree"
cap label var hdmn "month of award of highest degree"
cap label var dgryr "year of award of highest degree"
cap label var hdacy3 "year of award of highest degree (3 year intervals)"
cap label var hday5 "year of award of highest degree (5 year intervals)"
cap label var hdskl "reason for obtaining this degree: acquire further skills in field"
cap label var hdadv "reason for obtaining this degree: increase advancement opportunities"
cap label var hdcar "reason for obtaining this degree: further education before career"
cap label var hdchg "reason for obtaining this degree: change academic/occupational field"
cap label var hdem "reason for obtaining this degree: expected/required by employer"
cap label var hdlic "reason for obtaining this degree: licensure/certification"
cap label var hdot "reason for obtaining this degree: other"
cap label var hdint "reason for obtaining this degree: leisure/personal interest"
cap label var hdgrd "reason for obtaining this degree: prepare for graduate school/further education"
cap label var dgrdg "highest degree type"
cap label var ndgrmed "field of study for highest degree - best code"
cap label var nhdmedx "field of study for highest degree - reported code (do not use for analysis - use best code)"
cap label var ndgmemg "field of study for highest degree (major group)"
cap label var ndgmeng "field of study for highest degree (minor group)"
cap label var hdcarn "carnegie classification for school awarding highest degree - 1994 carnegie code"
cap label var hdcrn05c "carnegie classification for school awarding highest degree - 2005 carnegie code"
cap label var hdpbpr "public/private status of postsecondary institution awarding highest degree - 1994 carnegie value"
cap label var hdpbp05c "public/private status of postsecondary institution awarding highest degree - 2005 carnegie value"
cap label var hdrgn "location of school awarding highest degree (region code)"
cap label var hddgrus "location of school awarding highest degree (u.s./non-u.s.)"
cap label var hdst "location of school awarding highest degree (state/country code)"
cap label var d2skl "reason for obtaining this degree: acquire further skills in field"
cap label var d2adv "reason for obtaining this degree: increase advancement opportunities"
cap label var d2car "reason for obtaining this degree: further education before career"
cap label var d2chg "reason for obtaining this degree: change academic/occupational field"
cap label var d2em "reason for obtaining this degree: expected/required by employer"
cap label var d2lic "reason for obtaining this degree: licensure/certification"
cap label var d2ot "reason for obtaining this degree: other"
cap label var d2int "reason for obtaining this degree: leisure/personal interest"
cap label var d2grd "reason for obtaining this degree: prepare for graduate school/further education"
cap label var d2ayr "academic year of award for second highest degree"
cap label var d2mn "month of award of second highest degree"
cap label var d2yr "year of award of second highest degree"
cap label var d23yr "year of award of second highest degree (3 year intervals)"
cap label var d25yr "year of award of second highest degree (5 year intervals)"
cap label var d2dg "second highest degree type"
cap label var nd2med "field of study for second highest degree - best code"
cap label var nd2medx "field of study for second highest degree - reported code (do not use for analysis - use best code)"
cap label var nd2memg "field of study for second highest degree (major group)"
cap label var nd2meng "field of study for second highest degree (minor group)"
cap label var d2carn "carnegie classification for school awarding second highest degree - 1994 carnegie code"
cap label var d2crn05c "carnegie classification for school awarding second highest degree - 2005 carnegie code"
cap label var d2incd "institution code for school awarding second highest degree"
cap label var d2pbpr "public/private status of postsecondary institution awarding second highest degree - 1994 carnegie value"
cap label var d2pbp05c "public/private status of postsecondary institution awarding second highest degree - 2005 carnegie value"
cap label var d2rgn "location of school awarding second highest degree (region code)"
cap label var d2dgrus "location of school awarding second highest degree (u.s./non-u.s.)"
cap label var d2st "location of school awarding second highest degree (state/country code)"
cap label var d3skl "reason for obtaining this degree: acquire further skills in field"
cap label var d3adv "reason for obtaining this degree: increase advancement opportunities"
cap label var d3car "reason for obtaining this degree: further education before career"
cap label var d3chg "reason for obtaining this degree: change academic/occupational field"
cap label var d3em "reason for obtaining this degree: expected/required by employer"
cap label var d3lic "reason for obtaining this degree: licensure/certification"
cap label var d3ot "reason for obtaining this degree: other"
cap label var d3int "reason for obtaining this degree: leisure/personal interest"
cap label var d3grd "reason for obtaining this degree: prepare for graduate school/further education"
cap label var d3ayr "academic year of award for third highest degree"
cap label var d3mn "month of award of third highest degree"
cap label var d3yr "year of award of third highest degree"
cap label var d33yr "year of award of third highest degree (3 year intervals)"
cap label var d35yr "year of award of third highest degree (5 year intervals)"
cap label var d3dg "third highest degree type"
cap label var nd3med "field of study for third highest degree - best code"
cap label var nd3medx "field of study for third highest degree - reported code (do not use for analysis - use best code)"
cap label var nd3memg "field of study for third highest degree (major group)"
cap label var nd3meng "field of study for third highest degree (minor group)"
cap label var d3carn "carnegie classification for school awarding third highest degree - 1994 carnegie code"
cap label var d3crn05c "carnegie classification for school awarding third highest degree - 2005 carnegie code"
cap label var d3incd "institution code for school awarding third highest degree"
cap label var d3pbpr "public/private status of postsecondary institution awarding third highest degree - 1994 carnegie value"
cap label var d3pbp05c "public/private status of postsecondary institution awarding third highest degree - 2005 carnegie value"
cap label var d3rgn "location of school awarding third highest degree (region code)"
cap label var d3dgrus "location of school awarding third highest degree (u.s./non-u.s.)"
cap label var d3st "location of school awarding third highest degree (state/country code)"
cap label var d4skl "reason for obtaining this degree: acquire further skills in field"
cap label var d4adv "reason for obtaining this degree: increase advancement opportunities"
cap label var d4car "reason for obtaining this degree: further education before career"
cap label var d4chg "reason for obtaining this degree: change academic/occupational field"
cap label var d4em "reason for obtaining this degree: expected/required by employer"
cap label var d4lic "reason for obtaining this degree: licensure/certification"
cap label var d4ot "reason for obtaining this degree: other"
cap label var d4int "reason for obtaining this degree: leisure/personal interest"
cap label var d4grd "reason for obtaining this degree: prepare for graduate school/further education"
cap label var d4ayr "academic year of award for fourth highest degree"
cap label var d4mn "month of award of fourth highest degree"
cap label var d4yr "year of award of fourth highest degree"
cap label var d43yr "year of award of fourth highest degree (3 year intervals)"
cap label var d45yr "year of award of fourth highest degree (5 year intervals)"
cap label var d4dg "fourth highest degree type"
cap label var nd4med "field of study for fourth highest degree - best code"
cap label var nd4medx "field of study for fourth highest degree - reported code (do not use for analysis - use best code)"
cap label var nd4memg "field of study for fourth highest degree (major group)"
cap label var nd4meng "field of study for fourth highest degree (minor group)"
cap label var d4carn "carnegie classification for school awarding fourth highest degree - 1994 carnegie code"
cap label var d4crn05c "carnegie classification for school awarding fourth highest degree - 2005 carnegie code"
cap label var d4incd "institution code for school awarding fourth highest degree"
cap label var d4pbpr "public/private status of postsecondary institution awarding fourth highest degree - 1994 carnegie value"
cap label var d4pbp05c "public/private status of postsecondary institution awarding fourth highest degree - 2005 carnegie value"
cap label var d4rgn "location of school awarding fourth highest degree (region code)"
cap label var d4dgrus "location of school awarding fourth highest degree (u.s./non-u.s.)"
cap label var d4st "location of school awarding fourth highest degree (state/country code)"
cap label var d5skl "reason for obtaining this degree: acquire further skills in field"
cap label var d5adv "reason for obtaining this degree: increase advancement opportunities"
cap label var d5car "reason for obtaining this degree: further education before career"
cap label var d5chg "reason for obtaining this degree: change academic/occupational field"
cap label var d5em "reason for obtaining this degree: expected/required by employer"
cap label var d5lic "reason for obtaining this degree: licensure/certification"
cap label var d5ot "reason for obtaining this degree: other"
cap label var d5int "reason for obtaining this degree: leisure/personal interest"
cap label var d5grd "reason for obtaining this degree: prepare for graduate school/further education"
cap label var d5ayr "academic year of award for fifth highest degree"
cap label var d5mn "month of award of fifth highest degree"
cap label var d5yr "year of award of fifth highest degree"
cap label var d53yr "year of award of fifth highest degree (3 year intervals)"
cap label var d55yr "year of award of fifth highest degree (5 year intervals)"
cap label var d5dg "fifth highest degree type"
cap label var nd5med "field of study for fifth highest degree - best code"
cap label var nd5medx "field of study for fifth highest degree - reported code (do not use for analysis - use best code)"
cap label var nd5memg "field of study for fifth highest degree (major group)"
cap label var nd5meng "field of study for fifth highest degree (minor group)"
cap label var d5carn "carnegie classification for school awarding fifth highest degree - 1994 carnegie code"
cap label var d5crn05c "carnegie classification for school awarding fifth highest degree - 2005 carnegie code"
cap label var d5incd "institution code for school awarding fifth highest degree"
cap label var d5pbpr "public/private status of postsecondary institution awarding fifth highest degree - 1994 carnegie value"
cap label var d5pbp05c "public/private status of postsecondary institution awarding fifth highest degree - 2005 carnegie value"
cap label var d5rgn "location of school awarding fifth highest degree (region code)"
cap label var d5dgrus "location of school awarding fifth highest degree (u.s./non-u.s.)"
cap label var d5st "location of school awarding fifth highest degree (state/country code)"
cap label var sdrayr "academic year of award for first us s&e or health phd"
cap label var sdrmn "month of award of first us s&e or health phd"
cap label var sdryr "year of award of first us s&e or health phd"
cap label var sdr3yr "year of award of first us s&e or health phd (3 year intervals)"
cap label var sdr5yr "year of award of first us s&e or health phd (5 year intervals)"
cap label var nsdrmed "field of study for first us s&e or health phd"
cap label var nsdrmem "field of study for first us s&e or health phd (major group)"
cap label var nsdrmen "field of study for first us s&e or health phd (minor group)"
cap label var sdrcarn "carnegie classification for school awarding first us s&e or health  phd - 1994 carnegie code"
cap label var sdrcr05c "carnegie classification for school awarding first us s&e or health phd - 2005 carnegie code"
cap label var sdrincd "institution code for school awarding first us s&e or health phd"
cap label var sdrpbpr "public/private status of school awarding first us s&e or health phd - 1994 carnegie value"
cap label var sdrpb05c "public/private status of school awarding first us s&e or health phd - 2005 carnegie value"
cap label var sdrrgn "location of school awarding first us s&e or health phd degree (region code)"
cap label var sdrst "location of school awarding first us s&e or health phd (state/country code)"
cap label var age "age"
cap label var agegr "age group (5 year intervals)"
cap label var bthrgn "place of birth (region code)"
cap label var bthus "place of birth (u.s./non-u.s.)"
cap label var bthst "place of birth (state/country code)"
cap label var gender "gender"
cap label var racem "race"
cap label var racethm "race/ethnicity"
cap label var asian "asian racial background indicator"
cap label var black "black or african-american racial background indicator"
cap label var hispcat "new hispanic heritage categories"
cap label var hispanic "new hispanic origin indicator"
cap label var minrty "minority indicator"
cap label var native "american indian/alaska native racial background indicator"
cap label var pacific "native hawaiian or other pacific islander racial background indicator"
cap label var white "white racial background indicator"
cap label var resploc "respondent location"
cap label var resplo3 "3-digit respondent location (state/country code)"
cap label var resplcus "respondent location (u.s./non-u.s.)"
cap label var fnccd "country of foreign citizenship (country code)"
cap label var fncrgn "country of citizenship (region code)"
cap label var fninus "living in u.s. during reference week"
cap label var reside "living in u.s. or territory during reference week"
cap label var residev "living in u.s. or territory during reference week- other specify"
cap label var ctzn "citizenship or visa status"
cap label var ctzusin "u.s. citizenship status"
cap label var ctzfor "visa type for non-us citizens"
cap label var ctzus "type of us citizen"
cap label var chlvin "children living in household indicator (all ages)"
cap label var ch1218in "children living in household indicator: ages 12-18"
cap label var ch19in "children living in household indicator: age 19 or older"
cap label var ch25in "children living in household indicator: ages 2-5"
cap label var ch611in "children living in household indicator: ages 6-11"
cap label var chu2in "children living in household indicator: under age 2"
cap label var ch6in "children living in household indicator: under age 6"
cap label var ch1218 "number of children living in household: ages 12-18"
cap label var ch19 "number of children living in household: age 19 or older"
cap label var ch25 "number of children living in household: ages 2-5"
cap label var ch611 "number of children living in household: ages 6-11"
cap label var chu2 "number of children living in household: under age 2"
cap label var ch6 "number of children living in household: under age 6"
cap label var chun12 "children living in household indicator: under age 12"
cap label var marind "marital status indicator"
cap label var marsta "marital status"
cap label var eddad "father's education level"
cap label var edmom "mother's education level"
cap label var spot "technical expertise required by spouse/partner job: other"
cap label var spnat "technical expertise required by spouse/partner job: engineering, computer, math, natural sciences"
cap label var spsoc "technical expertise required by spouse/partner job: social sciences"
cap label var spowk "spouse or partner working?"
cap label var difcogn "physical abilities: degree of difficulty cognition"
cap label var difage "physical abilities: earliest age experienced difficulties"
cap label var difagegr "physical abilities: earliest age experienced difficulties (5 year intervals)"
cap label var difhear "physical abilities: degree of difficulty hearing"
cap label var hcapin "physical disabilities indicator"
cap label var diflift "physical abilities: degree of difficulty lifting"
cap label var difno "no difficulty with physical activities"
cap label var difsee "physical abilities: degree of difficulty seeing"
cap label var difbir "physical abilities: experienced difficulties since birth"
cap label var difwalk "physical abilities: degree of difficulty walking"
cap label var refid "reference/id number"
cap label var cohort "survey cohort"
cap label var surid "survey identifier"
cap label var srvmode "survey mode"
cap label var refyr "survey year"
cap label var valind "valid response indicator"
cap label var wtsurvy "final survey-specific weight"
